export const headphones = [
  {
    img: "./assets/1.png",
    title: "Apple BYZ S852I",
    price: 2927,
    oldPrice: 3580,
    rate: 4.7,
    id: 1,
    type: "wired",
  },
  {
    img: "./assets/2.png",
    title: "Sony WH-1000XM4",
    price: 3499,
    rate: 4.8,
    id: 2,
    type: "wired",
  },
  {
    img: "./assets/3.png",
    title:
      "Bose QuietComfort 35 II серый 2.0, охватывающие, Bluetooth, проводной, кабель - 1.2 м",
    price: 2999,
    rate: 4.6,
    id: 3,
    type: "wired",
  },
  {
    img: "./assets/1.png",
    title: "Huawei pura 70",
    price: 2879,
    rate: 4.3,
    id: 4,
    type: "wired",
  },
  {
    img: "./assets/2.png",
    title: "JBL Tune 510WS",
    price: 2920,
    oldPrice: 4620,
    rate: 4.4,
    id: 5,
    type: "wired",
  },
  {
    img: "./assets/3.png",
    title: "JBL T110",
    price: 3489,
    rate: 4.8,
    id: 6,
    type: "wired",
  },
  {
    img: "./assets/5.png",
    title: "Tune 225 tws",
    price: 3999,
    rate: 4.9,
    id: 7,
    type: "wireless",
  },
  {
    img: "./assets/7.png",
    title: "Tune 120 TWS",
    price: 3879,
    rate: 4.2,
    id: 8,
    type: "wireless",
  },
  {
    img: "./assets/8.png",
    title: "AirPods pro",
    price: 3920,
    rate: 4.4,
    id: 9,
    type: "wireless",
  },
];
